### ISSUE TITLE
Aggregation binding not working

### ISSUE THREAD

**Issue by dfenerski** [wozjac/jsono-model#1]
We found this and decided to take it up for a test because we liked the idea and the implementation seemed neat. However when doing an aggregation binding, ui5 breaks during an attempt to call `slice`. 
![image](https://user-images.githubusercontent.com/48520530/181095723-ef8907e3-78eb-4201-a26f-b9b389ad8e52.png)

Changing the `makeProxyFor` function to this removes the error from the console
![image](https://user-images.githubusercontent.com/48520530/181098570-96e48156-3cb3-4fdf-9639-4b8e8ea010e1.png)

Am I missing something? Thanks for the support!

**Comment by dfenerski** [comment]
After testing around, aggregation binding does work.
The issue was caused by an experimental modification made by us that allows bindings to methods of the supplied class. 

Sorry for the trouble!

**Comment by wozjac** [comment]
Hello,

no problem - glad to hear it works!
