### ISSUE TITLE
Nested proxies cause performance issues

### ISSUE THREAD

**Issue by dfenerski** [wozjac/jsono-model#2]
Hi,

I've noticed if you invoke `model.arrayProp.sort()` it wraps the array objects in a proxy and it continues to do this with each call. If the sort is in a function and it gets called multiple times, the array objects continue to be nested in more and more proxies, which after a couple of calls causes ui5 to completely freeze when accessing them.

Am I doing something wrong? Any help on this is greatly appreciated.

Best regards,

Dimitar

**Comment by wozjac** [comment]
Hi Dimitar,
need to check this.

Best Regards
Jacek

**Comment by dfenerski** [comment]
Thanks for the reply, @wozjac!,

I could narrow it down a bit. It is not a problem with `sort` itself, but rather re-saving a returned `Proxy` from the `get`.

E.g:
<pre>
    model.arrayProp = model.arrayProp;
    model.arrayProp.sort();
    model.arrayProp = model.arrayProp.map();
    ...
</pre>

There is a workaround because proxies don't live in JSON-land but it is quite ugly:
<pre>
    model.arrayProp = JSON.parse(JSON.stringify(model.arrayProp));
</pre>


I am not really sure on how to proceed with tackling this. 

Would be really grateful for any help.

Thank you and BR

Dimitar

**Comment by wozjac** [comment]
Hi @dfenerski 

checked quickly - this is one is tricky, but not sure if this "get" interceptor could do better here - need more checks and longer debugging. 

BR,
Jacek

**Comment by wozjac** [comment]
@dfenerski 
The problem was that in fact each get interceptor was creating a new Proxy.
Just committed and pushed a change, branch "fix-proxied-get", still need to test it for a while. 

BR,
Jacek

**Comment by dfenerski** [comment]
@wozjac Thank you for the assistance! The fix seems to solve the problem. Before opening the issue, I've tested a solution where instead of a instance member WeakMap I tracked created proxies in a static member array, but this seemed to slow things down quite a bit. With an instance member things do not seem grim but there still may exist some performance overhead because of all the checks, or?

Thanks again for your support and sorry for the trouble.

P.S.
I've noticed a weird issue where the the JSONO has trouble returning Proxies for Object.frozen objects. Should I investigate this and share info about it?

**Comment by wozjac** [comment]
Hi @dfenerski 
thanks for all issues you reported! If you find anything else please let me know.

BR,
Jacek

**Comment by dfenerski** [comment]
Hi @wozjac ,

Even with the fix, stuff like `model.arrayProp = [...model.arrayProp, someObj]` or just `model.arrayProp = [...model.arrayProp]` still cause creation of nested proxies leading to the same performance problem.

Going back to JSON serialization for now.

Thanks and BR

**Comment by wozjac** [comment]
Hi @dfenerski 

thanks for reporting, I'll check if there is a workaround.

BR
Jacek
